import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { FindOptionsWhere, ILike, Repository } from 'typeorm';
import { DrugReference } from '../../common/entities/drug-reference.entity';
import { NotebookNote } from '../../common/entities/notebook-note.entity';
import { StudentStudyPlan } from '../../common/entities/student-study-plan.entity';
import { AuthenticatedUser } from '../auth/strategies/jwt.strategy';
import { UserRole } from '../users/entities/user.entity';
import { CreateNotebookNoteDto, DrugReferenceQueryDto, NotebookQueryDto, SaveDrugReferenceDto, UpdateDrugReferenceDto, UpdateNotebookNoteDto, UpdateStudyPlanDto } from './dtos/workspace.dto';

@Injectable()
export class WorkspaceService {
 constructor(@InjectRepository(NotebookNote) private readonly notes:Repository<NotebookNote>,@InjectRepository(StudentStudyPlan) private readonly plans:Repository<StudentStudyPlan>,@InjectRepository(DrugReference) private readonly drugs:Repository<DrugReference>){}
 async listNotes(userId:string,query:NotebookQueryDto){const page=query.page??1,limit=query.limit??20;const builder=this.notes.createQueryBuilder('note').where('note.user_id=:userId',{userId}).orderBy('note.updated_at','DESC').skip((page-1)*limit).take(limit);if(query.note_type)builder.andWhere('note.note_type=:type',{type:query.note_type});if(query.search)builder.andWhere('(note.title ILIKE :search OR note.content ILIKE :search)',{search:`%${query.search}%`});const [data,total]=await builder.getManyAndCount();return{data,page,limit,total,total_pages:Math.ceil(total/limit)};}
 createNote(userId:string,dto:CreateNotebookNoteDto){return this.notes.save(this.notes.create({userId,title:dto.title.trim(),noteType:dto.note_type,content:dto.content.trim(),metadata:dto.metadata??{}}));}
 async updateNote(userId:string,id:string,dto:UpdateNotebookNoteDto){const note=await this.requireNote(userId,id);if(dto.title!==undefined)note.title=dto.title.trim();if(dto.note_type!==undefined)note.noteType=dto.note_type;if(dto.content!==undefined)note.content=dto.content.trim();if(dto.metadata!==undefined)note.metadata=dto.metadata;return this.notes.save(note);}
 async removeNote(userId:string,id:string){await this.notes.remove(await this.requireNote(userId,id));}
 private async requireNote(userId:string,id:string){const note=await this.notes.findOne({where:{id,userId}});if(!note)throw new NotFoundException('Notebook note not found');return note;}
 async getPlan(studentId:string){let plan=await this.plans.findOne({where:{studentId}});if(plan)return plan;await this.plans.createQueryBuilder().insert().values({studentId,targetExam:null,examDate:null,dailyQuestionTarget:20,weeklyHoursTarget:10,dailyFlashcardTarget:20,preferences:{}}).orIgnore().execute();plan=await this.plans.findOne({where:{studentId}});if(!plan)throw new NotFoundException('Student study plan could not be initialized');return plan;}
 async updatePlan(studentId:string,dto:UpdateStudyPlanDto){const plan=await this.getPlan(studentId);if(dto.target_exam!==undefined)plan.targetExam=dto.target_exam.trim()||null;if(dto.exam_date!==undefined)plan.examDate=dto.exam_date;if(dto.daily_question_target!==undefined)plan.dailyQuestionTarget=dto.daily_question_target;if(dto.weekly_hours_target!==undefined)plan.weeklyHoursTarget=dto.weekly_hours_target;if(dto.daily_flashcard_target!==undefined)plan.dailyFlashcardTarget=dto.daily_flashcard_target;if(dto.preferences!==undefined)plan.preferences=dto.preferences;return this.plans.save(plan);}
 async listDrugs(actor:AuthenticatedUser,query:DrugReferenceQueryDto){const page=query.page??1,limit=query.limit??20;const where:FindOptionsWhere<DrugReference>={};if(actor.role===UserRole.STUDENT)where.isPublished=true;if(query.category)where.category=query.category;if(query.search)where.name=ILike(`%${query.search}%`);const [data,total]=await this.drugs.findAndCount({where,order:{name:'ASC'},skip:(page-1)*limit,take:limit});return{data,page,limit,total,total_pages:Math.ceil(total/limit)};}
 async getDrug(actor:AuthenticatedUser,slug:string){const drug=await this.drugs.findOne({where:{slug}});if(!drug||(actor.role===UserRole.STUDENT&&!drug.isPublished))throw new NotFoundException('Drug reference not found');return drug;}
 async createDrug(actor:AuthenticatedUser,dto:SaveDrugReferenceDto){this.assertEditor(actor);const slug=dto.slug.trim().toLowerCase();if(await this.drugs.findOne({where:{slug}}))throw new ConflictException('Drug reference slug already exists');return this.drugs.save(this.drugs.create({name:dto.name.trim(),slug,category:dto.category.trim(),drugClass:dto.drug_class.trim(),content:dto.content,isPublished:dto.is_published??false,createdBy:actor.userId}));}
 async updateDrug(actor:AuthenticatedUser,id:string,dto:UpdateDrugReferenceDto){this.assertEditor(actor);const drug=await this.drugs.findOne({where:{id}});if(!drug)throw new NotFoundException('Drug reference not found');if(dto.slug!==undefined){const slug=dto.slug.trim().toLowerCase();const duplicate=await this.drugs.findOne({where:{slug}});if(duplicate&&duplicate.id!==id)throw new ConflictException('Drug reference slug already exists');drug.slug=slug;}if(dto.name!==undefined)drug.name=dto.name.trim();if(dto.category!==undefined)drug.category=dto.category.trim();if(dto.drug_class!==undefined)drug.drugClass=dto.drug_class.trim();if(dto.content!==undefined)drug.content=dto.content;if(dto.is_published!==undefined)drug.isPublished=dto.is_published;return this.drugs.save(drug);}
 private assertEditor(actor:AuthenticatedUser){if(actor.role===UserRole.STUDENT)throw new ForbiddenException('Only instructors and administrators can manage drug references');}
}
