import type { AnatomyStructure, AnatomySystem } from "./anatomy-viewer";

import hand from "./hand.json";
import lowerLimb from "./lower-limb.json";
import skeleton from "./skeleton.json";
import skullBase from "./skull-base.json";
import skullExploded from "./skull-exploded.json";
import skull from "./skull.json";
import upperLimb from "./upper-limb.json";
import vertebrae from "./vertebrae.json";

export type AnatomyRegion = {
  region: string;
  label: string;
  structures: AnatomyStructure[];
  systems: AnatomySystem[];
  /** Muscle textures stripped at build time because they are CC BY-NC-SA, not CC BY-SA. */
  nonCommercialTexturesRemoved: string[];
};

/**
 * Viewable regions, in teaching order rather than alphabetical. Each entry is generated by
 * scripts/anatomy/prepare-model.mjs from the model that actually shipped, so the structure
 * list and the .glb cannot drift apart.
 */
export const REGIONS: Record<string, AnatomyRegion> = {
  skeleton,
  skull,
  "skull-exploded": skullExploded,
  "skull-base": skullBase,
  vertebrae,
  "upper-limb": upperLimb,
  "lower-limb": lowerLimb,
  hand,
};

export const REGION_SLUGS = Object.keys(REGIONS);
export const getRegion = (slug: string): AnatomyRegion | undefined => REGIONS[slug];
