"use client";

import Link from "next/link";import { useEffect, useState } from "react";import { FiBookOpen, FiEdit3, FiPlus, FiTrash2 } from "react-icons/fi";import { useAuth } from "./auth-provider";import { Panel, ProductShell } from "./product-shell";import "./product-pages.css";
type Note={id:string;title:string;noteType:string;content:string;metadata:Record<string,unknown>;createdAt:string;updatedAt:string};type Page<T>={data:T[];total:number};
export function ConnectedNotebookPage(){const {request}=useAuth();const [notes,setNotes]=useState<Note[]>([]);const [selected,setSelected]=useState<Note|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{let active=true;void request<Page<Note>>("/notebook/notes?limit=100").then(result=>{if(active){setNotes(result.data);setSelected(result.data[0]||null);}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Unable to load notebook.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[request]);
 async function remove(id:string){try{await request(`/notebook/notes/${id}`,{method:"DELETE"});setNotes(current=>current.filter(note=>note.id!==id));setSelected(current=>current?.id===id?null:current);}catch(cause){setError(cause instanceof Error?cause.message:"Unable to delete note.");}}
 return <ProductShell search="Search your notebook"><main className="pp-page"><div className="pp-title"><div><h1>Notebook</h1><p>Your private notes, stored per authenticated account.</p></div><Link className="pp-button" href="/notebook/new"><FiPlus/> New note</Link></div>{error&&<p className="form-error" role="alert">{error}</p>}{loading?<div className="product-auth-loading">Loading notebook…</div>:!notes.length?<Panel title="Your notebook is empty"><FiBookOpen/><p>Create your first note. No demonstration notes are inserted automatically.</p><Link className="pp-button" href="/notebook/new">Create note</Link></Panel>:<div className="notebook-layout"><aside className="pp-side"><h3>MY NOTES</h3>{notes.map(note=><button className={selected?.id===note.id?"active":""} onClick={()=>setSelected(note)} key={note.id}><FiEdit3/>{note.title}</button>)}</aside><Panel title={selected?.title}>{selected&&<><small>{selected.noteType.replaceAll("_"," ")} · Updated {new Date(selected.updatedAt).toLocaleString()}</small><p className="note-content">{selected.content}</p></>}</Panel><Panel title="Actions">{selected&&<button className="pp-button secondary" onClick={()=>void remove(selected.id)}><FiTrash2/> Delete note</button>}</Panel></div>}</main></ProductShell>}

