"use client";

import { ApiError } from "@/lib/api";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { FiCheck, FiSave } from "react-icons/fi";
import { useAuth } from "./auth-provider";
import { Panel, ProductShell } from "./product-shell";
import "./product-pages.css";

type Course={id:string;courseName:string};type Lecture={id:string;title:string;lectureNumber:number};type Week={id:string;title:string|null;weekNumber:number;lectures:Lecture[]};type Page<T>={data:T[]};type Deck={id:string;title:string;isPublished:boolean};

export function ConnectedInstructorFlashcardsPage(){
 const router=useRouter();const {user,request}=useAuth();const [courses,setCourses]=useState<Course[]>([]);const [courseId,setCourseId]=useState("");const [weeks,setWeeks]=useState<Week[]>([]);const [lectureId,setLectureId]=useState("");const [front,setFront]=useState("");const [back,setBack]=useState("");const [title,setTitle]=useState("");const [difficulty,setDifficulty]=useState("MEDIUM");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{if(user?.role==="STUDENT")router.replace("/dashboard");},[user,router]);
 useEffect(()=>{let active=true;void request<Page<Course>>("/academic/courses?limit=100").then(result=>{if(active){setCourses(result.data);setCourseId(result.data[0]?.id||"");}}).catch(cause=>{if(active)setError(cause instanceof ApiError?cause.message:"Unable to load courses.");}).finally(()=>{if(active)setLoading(false)});return()=>{active=false};},[request]);
 useEffect(()=>{if(!courseId)return;let active=true;void request<Week[]>(`/academic/courses/${courseId}/weeks`).then(result=>{if(active){setWeeks(result);setLectureId(result.flatMap(week=>week.lectures)[0]?.id||"");}}).catch(cause=>{if(active)setError(cause instanceof ApiError?cause.message:"Unable to load course lectures.");});return()=>{active=false};},[courseId,request]);
 const selected=useMemo(()=>weeks.flatMap(week=>week.lectures.map(lecture=>({week,lecture}))).find(item=>item.lecture.id===lectureId),[weeks,lectureId]);
 async function save(publish:boolean){if(!courseId||!lectureId||!front.trim()||!back.trim()){setError("Choose a lecture and complete both sides of the card.");return;}setSaving(true);setError(null);setMessage(null);try{const deck=await request<Deck>("/flashcards/decks",{method:"POST",body:{course_id:courseId,lecture_id:lectureId,title:title.trim()||`${selected?.lecture.title||"Lecture"} flashcards`,description:`Instructor flashcards for ${selected?.lecture.title||"the selected lecture"}`}});await request(`/flashcards/decks/${deck.id}/cards`,{method:"POST",body:{title:title.trim()||front.trim().slice(0,120),front_content:front.trim(),back_content:back.trim(),difficulty}});if(publish)await request(`/flashcards/decks/${deck.id}`,{method:"PUT",body:{is_published:true}});setMessage(publish?"Deck and card published to students.":"Draft deck and card saved.");setFront("");setBack("");setTitle("");}catch(cause){setError(cause instanceof ApiError?cause.message:"Unable to save this flashcard.");}finally{setSaving(false);}}
 return <ProductShell search="Search decks, lectures, or cards"><main className="pp-page instructor-flashcards"><div className="pp-title hero"><div><small className="page-eyebrow">INSTRUCTOR WORKSPACE</small><h1>Flashcard Builder</h1><p>Create a focused front-and-back card, attach it to your assigned course, then save or publish it.</p></div></div>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-success" role="status">{message}</p>}{loading?<div className="product-auth-loading">Loading your assigned curriculum…</div>:<div className="flashcard-builder-layout"><aside className="builder-decks"><label>Course<select value={courseId} onChange={event=>setCourseId(event.target.value)}>{courses.map(course=><option value={course.id} key={course.id}>{course.courseName}</option>)}</select></label>{weeks.map(week=><section key={week.id}><b>Week {week.weekNumber}</b><small>{week.title}</small>{week.lectures.map(lecture=><button className={lectureId===lecture.id?"active":""} onClick={()=>setLectureId(lecture.id)} key={lecture.id}>{lecture.lectureNumber}. {lecture.title}</button>)}</section>)}</aside><div className="card-editor"><Panel><div className="editor-title"><div><small>{selected?`WEEK ${selected.week.weekNumber} · LECTURE ${selected.lecture.lectureNumber}`:"SELECT A LECTURE"}</small><h2>Create Flashcard</h2></div></div><label>Card title<input value={title} onChange={event=>setTitle(event.target.value)} maxLength={200}/></label><label>Front <small>Use one definition, title, or focused question.</small><textarea value={front} onChange={event=>setFront(event.target.value)} maxLength={50000}/></label><label>Back <small>Give a concise explanation or summary.</small><textarea value={back} onChange={event=>setBack(event.target.value)} maxLength={50000}/></label><label>Difficulty<select value={difficulty} onChange={event=>setDifficulty(event.target.value)}><option>EASY</option><option>MEDIUM</option><option>HARD</option></select></label><div className="editor-actions"><button className="pp-button secondary" disabled={saving} onClick={()=>void save(false)}><FiSave/> Save draft</button><button className="pp-button" disabled={saving} onClick={()=>void save(true)}><FiCheck/> Publish to students</button></div></Panel></div><aside className="deck-management"><Panel title="Publishing rules"><p>The backend verifies that you are assigned to the selected course.</p><p>A published deck requires at least one active card.</p><p>Published cards become visible in student review queues.</p></Panel></aside></div>}</main></ProductShell>;
}
