"use client";

import { useAuth } from "./auth-provider";
import { Panel, ProductShell } from "./product-shell";
import { useEffect, useMemo, useState } from "react";
import { FiArrowRight, FiBookOpen, FiCheck, FiClipboard, FiLayers } from "react-icons/fi";
import { useRouter } from "next/navigation";
import "./product-pages.css";

type Bundle={id:string;title:string;read_only?:boolean};
type Course={id:string;courseName:string};
type PastExam={id:string;title:string;description:string|null;durationMinutes:number|null;totalMarks:string|null;testType:string;availableFrom:string|null;availableUntil:string|null};
type BundleContent={bundle:Bundle;courses:Array<Course & {weeks:Week[]}>;past_exams:PastExam[]};
type Lecture={id:string;title:string;lectureNumber:number;question_count:number};
type Week={id:string;title:string|null;weekNumber:number;lectures:Lecture[]};
type Catalog={course:Course;weeks:Week[]};
type Generated={test:{id:string};attempt:{id:string};question_count:number};

export function ConnectedAssessmentsPage(){
 const {request}=useAuth();const router=useRouter();
 const [bundles,setBundles]=useState<Bundle[]>([]),[bundleId,setBundleId]=useState(""),[bundleContent,setBundleContent]=useState<BundleContent|null>(null);
 const [courses,setCourses]=useState<Course[]>([]),[courseId,setCourseId]=useState(""),[catalog,setCatalog]=useState<Catalog|null>(null);
 const [selected,setSelected]=useState<string[]>([]),[count,setCount]=useState(20),[difficulty,setDifficulty]=useState(""),[mode,setMode]=useState("TUTOR");
 const [loading,setLoading]=useState(true),[generating,setGenerating]=useState(false),[error,setError]=useState<string|null>(null),[tab,setTab]=useState<"bank"|"past"|"final">("bank");
 useEffect(()=>{let active=true;void request<Bundle[]>("/bundles/mine").then(result=>{if(active){setBundles(result);setBundleId(result[0]?.id||"");if(!result.length)setLoading(false);}}).catch(cause=>{if(active){setError(cause instanceof Error?cause.message:"Unable to load your bundles.");setLoading(false);}});return()=>{active=false};},[request]);
 useEffect(()=>{if(!bundleId){setBundleContent(null);setCourses([]);setCourseId("");setLoading(false);return;}let active=true;setLoading(true);void request<BundleContent>(`/bundles/${bundleId}/content`).then(result=>{if(active){setBundleContent(result);setCourses(result.courses);setCourseId(result.courses[0]?.id||"");setCatalog(null);setSelected([]);setError(null);}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Unable to load bundle content.");}).finally(()=>{if(active)setLoading(false)});return()=>{active=false};},[bundleId,request]);
 useEffect(()=>{if(!bundleId||!courseId)return;let active=true;void request<Catalog>(`/tests/practice/catalog?bundle_id=${bundleId}&course_id=${courseId}`).then(result=>{if(active){setCatalog(result);setSelected([]);setError(null);}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Unable to load the question catalog.");});return()=>{active=false};},[bundleId,courseId,request]);
 const lectures=useMemo(()=>catalog?.weeks.flatMap(week=>week.lectures.map(lecture=>({week,lecture})))||[],[catalog]);
 const chosen=lectures.filter(item=>selected.includes(item.lecture.id));const available=chosen.reduce((sum,item)=>sum+item.lecture.question_count,0);const totalAvailable=lectures.reduce((sum,item)=>sum+item.lecture.question_count,0);const pastExamCount=bundleContent?.past_exams.length||0;const weekCount=catalog?.weeks.length||0;
 function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);}
 function toggleWeek(ids:string[]){setSelected(current=>ids.every(id=>current.includes(id))?current.filter(id=>!ids.includes(id)):[...new Set([...current,...ids])]);}
 async function startPastExam(test:PastExam){setGenerating(true);setError(null);try{const attempt=await request<{id:string}>(`/tests/${test.id}/attempts`,{method:"POST",body:{test_mode:test.durationMinutes?"TIMED":"TUTOR"}});router.push(`/mock-exam/session?attempt=${attempt.id}&test=${test.id}&source=past-exams`);}catch(cause){setError(cause instanceof Error?cause.message:"Unable to start this past exam.");}finally{setGenerating(false);}}
 async function generate(final=false){const lectureIds=final?lectures.map(item=>item.lecture.id):selected;const questionCount=final?200:Math.min(count,available);if(!lectureIds.length||questionCount<1){setError("Select at least one lecture that contains questions.");return;}setGenerating(true);setError(null);try{const result=await request<Generated>("/tests/practice/generate",{method:"POST",body:{bundle_id:bundleId,lecture_ids:lectureIds,question_count:questionCount,difficulty:difficulty||undefined,test_mode:final?"TIMED":mode,duration_minutes:final?240:mode==="TIMED"?Math.max(10,questionCount*2):undefined}});router.push(`/mock-exam/session?attempt=${result.attempt.id}&test=${result.test.id}`);}catch(cause){setError(cause instanceof Error?cause.message:"Unable to generate this assessment.");}finally{setGenerating(false);}}
 return <ProductShell search="Search courses, weeks, or lectures"><main className="pp-page assessment-reference-page"><header className="assessment-reference-header"><div><span className="page-eyebrow">BUNDLE ASSESSMENT WORKSPACE</span><h1>Questions &amp; Assessments</h1><p>Practise by academic structure or work through complete examinations assigned to your bundle.</p></div><section className="assessment-summary"><div><FiClipboard/><span><b>{totalAvailable}</b><small>Available questions</small></span></div><div><FiBookOpen/><span><b>{weekCount}</b><small>Published weeks</small></span></div><div><FiCheck/><span><b>{pastExamCount}</b><small>Past exams</small></span></div><div><FiLayers/><span><b>{selected.length}</b><small>Selected lectures</small></span></div></section></header>
  <div className="assessment-tabs"><button className={tab==="bank"?"active":""} onClick={()=>setTab("bank")}>Question Banks</button><button className={tab==="past"?"active":""} onClick={()=>setTab("past")}>Past Exams</button><button className={tab==="final"?"active":""} onClick={()=>setTab("final")}>Final Exam</button></div>
  {error&&<p className="form-error" role="alert">{error}</p>}{!loading&&!bundles.length?<Panel title="No bundle access"><p>Join or receive a bundle before opening its question bank.</p></Panel>:loading?<div className="product-auth-loading">Loading your curriculum…</div>:tab==="past"?<div className="real-exams-layout"><div className="exam-grid">{bundleContent?.past_exams.length?bundleContent.past_exams.map(test=><Panel key={test.id} className="real-exam-card" title={test.title}><span className="pp-chip">{test.testType.replaceAll("_"," ")}</span><p>{test.description||"No description has been published."}</p><dl><div><dt>Duration</dt><dd>{test.durationMinutes?`${test.durationMinutes} minutes`:"Tutor mode"}</dd></div><div><dt>Total marks</dt><dd>{test.totalMarks||"Calculated from questions"}</dd></div></dl><button className="pp-button" disabled={generating||Boolean(bundleContent?.bundle.read_only)} onClick={()=>void startPastExam(test)}>{generating?"Starting…":"Start exam"}<FiArrowRight/></button></Panel>):<Panel title="No past exams published"><p>This bundle does not have a published past exam yet.</p></Panel>}</div><Panel title="Bundle access"><p>Only exams explicitly assigned to <b>{bundleContent?.bundle.title}</b> appear here. Expired bundles remain visible but cannot start new attempts.</p></Panel></div>:tab==="final"?<div className="final-questions-page"><Panel className="final-exam-hero"><span><FiClipboard/></span><div><small>COMPLETE COURSE ASSESSMENT</small><h1>Make a Final Exam</h1><p>Generate 200 questions across every lecture in {catalog?.course.courseName||"the selected course"}.</p></div><aside><b>200</b><small>questions · 240 minutes</small><button disabled={generating||totalAvailable<200||Boolean(bundleContent?.bundle.read_only)} className="pp-button" onClick={()=>void generate(true)}>{generating?"Generating…":"Start final exam"}<FiArrowRight/></button></aside></Panel>{totalAvailable<200&&<Panel title="Not enough questions yet"><p>This course currently has {totalAvailable} active question-bank questions. A final exam requires 200 unique questions.</p></Panel>}</div>:
  <div className="question-bank-layout"><aside className="academic-filter"><div className="filter-title"><span>ACADEMIC STRUCTURE</span><button onClick={()=>setSelected([])}>Clear</button></div><label>Bundle<select value={bundleId} onChange={event=>setBundleId(event.target.value)}>{bundles.map(bundle=><option value={bundle.id} key={bundle.id}>{bundle.title}{bundle.read_only?" · read-only":""}</option>)}</select></label><label>Course<select value={courseId} onChange={event=>setCourseId(event.target.value)}>{courses.map(course=><option value={course.id} key={course.id}>{course.courseName}</option>)}</select></label><div className="structure-tree">{catalog?.weeks.map(week=>{const ids=week.lectures.filter(item=>item.question_count>0).map(item=>item.id);return <section key={week.id}><label className="week-select"><input type="checkbox" disabled={!ids.length} checked={Boolean(ids.length)&&ids.every(id=>selected.includes(id))} onChange={()=>toggleWeek(ids)}/><span><b>Week {week.weekNumber}</b><small>{week.title||"Untitled week"}</small></span><em>{week.lectures.reduce((sum,item)=>sum+item.question_count,0)} Qs</em></label><div className="lecture-options">{week.lectures.map(lecture=><label key={lecture.id}><input type="checkbox" disabled={!lecture.question_count} checked={selected.includes(lecture.id)} onChange={()=>toggle(lecture.id)}/><span><b>{lecture.lectureNumber}. {lecture.title}</b><small>{lecture.question_count} questions</small></span></label>)}</div></section>})}</div></aside>
   <div className="pp-main bank-main"><div className="bank-heading"><div><span>CUSTOM QUIZ FROM LECTURES</span><h2>Choose what you want to be tested on</h2><p>Only active questions linked to the selected lectures can enter the generated quiz.</p></div><div><b>{chosen.length}</b><small>lectures selected</small></div></div>{chosen.length?<div className="selected-scope">{chosen.map(({week,lecture})=><article key={lecture.id}><span><FiBookOpen/></span><div><small>Week {week.weekNumber}</small><b>{lecture.title}</b><em>{lecture.question_count} available questions</em></div><button onClick={()=>toggle(lecture.id)}>×</button></article>)}</div>:<Panel title="No lectures selected"><p>Select one or more lectures from the curriculum tree.</p></Panel>}<Panel title="Question coverage"><b className="pp-big">{available}</b><p>unique questions available in the current scope.</p></Panel></div>
   <Panel className="quiz-builder" title="Custom quiz"><div className="builder-count"><b>{Math.min(count,available)}</b><span>questions in this quiz</span></div><label>Questions<div className="limit-options">{[10,20,40].map(value=><button type="button" className={count===value?"active":""} onClick={()=>setCount(value)} key={value}>{value}</button>)}</div></label><label>Difficulty<select value={difficulty} onChange={event=>setDifficulty(event.target.value)}><option value="">Mixed</option><option>EASY</option><option>MEDIUM</option><option>HARD</option></select></label><label>Mode<select value={mode} onChange={event=>setMode(event.target.value)}><option value="TUTOR">Tutor · explanation after answer</option><option value="TIMED">Timed · results after submit</option></select></label><button className="pp-button" disabled={generating||!selected.length||available<1||Boolean(bundleContent?.bundle.read_only)} onClick={()=>void generate()}>{generating?"Generating…":"Generate quiz"}<FiArrowRight/></button><p><FiCheck/> Questions are sampled without duplicates inside a database transaction.</p></Panel></div>}</main></ProductShell>;
}
