"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { FiBookOpen, FiChevronRight, FiFileText } from "react-icons/fi";
import { useAuth } from "./auth-provider";
import { Panel, ProductShell, Progress } from "./product-shell";
import "./product-pages.css";

type Bundle={id:string;title:string;read_only?:boolean};
type Lecture={id:string;title:string;description:string|null;lectureNumber:number;question_count:number;flashcard_deck_count:number;resource_count:number};
type Week={id:string;weekNumber:number;title:string|null;description:string|null;lectures:Lecture[]};
type Course={id:string;courseName:string;courseCode:string;description:string|null;weeks:Week[]};
type Content={bundle:Bundle;courses:Course[]};

export function ConnectedRoundsPage(){
 const {request}=useAuth();const [bundles,setBundles]=useState<Bundle[]>([]);const [bundleId,setBundleId]=useState("");const [courses,setCourses]=useState<Course[]>([]);const [courseId,setCourseId]=useState("");const [weeks,setWeeks]=useState<Week[]>([]);const [selected,setSelected]=useState<Lecture|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{let active=true;void request<Bundle[]>("/bundles/mine").then(result=>{if(active){setBundles(result);setBundleId(result[0]?.id||"");if(!result.length)setLoading(false);}}).catch(cause=>{if(active){setError(cause instanceof Error?cause.message:"Unable to load your bundles.");setLoading(false);}});return()=>{active=false};},[request]);
 useEffect(()=>{if(!bundleId)return;let active=true;setLoading(true);void request<Content>(`/bundles/${bundleId}/content`).then(result=>{if(active){setCourses(result.courses);setCourseId(result.courses[0]?.id||"");setError(null);}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Unable to load bundle curriculum.");}).finally(()=>{if(active)setLoading(false)});return()=>{active=false};},[bundleId,request]);
 useEffect(()=>{const course=courses.find(item=>item.id===courseId);const nextWeeks=course?.weeks||[];setWeeks(nextWeeks);setSelected(nextWeeks.flatMap(item=>item.lectures)[0]||null);},[courseId,courses]);
 const course=courses.find(item=>item.id===courseId);const lectures=weeks.flatMap(week=>(week.lectures||[]).map(lecture=>({week,lecture})));return <ProductShell search="Search courses or lectures"><main className="pp-page"><div className="pp-title"><div><h1>Rounds &amp; Lectures</h1><p>Open only the weeks and lectures included in your active bundle.</p></div><div className="round-filters"><label>Bundle<select value={bundleId} onChange={event=>setBundleId(event.target.value)}>{bundles.map(item=><option key={item.id} value={item.id}>{item.title}{item.read_only?" · read-only":""}</option>)}</select></label><label>Course<select value={courseId} onChange={event=>setCourseId(event.target.value)}>{courses.map(item=><option key={item.id} value={item.id}>{item.courseCode} · {item.courseName}</option>)}</select></label></div></div>{error&&<p className="form-error" role="alert">{error}</p>}{loading?<div className="product-auth-loading">Loading curriculum…</div>:!bundles.length?<Panel title="No bundle access"><p>Join or receive a bundle before opening rounds.</p></Panel>:!course?<Panel title="No courses available"><p>This bundle does not contain an available course.</p></Panel>:<div className="study-guide-layout"><aside className="guide-course-nav"><div className="guide-course"><small>COURSE</small><b>{course.courseName}</b></div>{weeks.map(week=><section key={week.id}><div><b>Week {week.weekNumber}</b><small>{week.title||"Untitled week"}</small></div>{(week.lectures||[]).map(lecture=><button className={selected?.id===lecture.id?"active":""} onClick={()=>setSelected(lecture)} key={lecture.id}><FiBookOpen/><span>{lecture.lectureNumber}. {lecture.title}</span><FiChevronRight/></button>)}</section>)}</aside><article className="guide-content">{selected?<><div className="guide-hero"><span><FiBookOpen/></span><div><small>LECTURE {selected.lectureNumber}</small><h1>{selected.title}</h1><p>{selected.description||"No description has been published for this lecture."}</p></div></div><Panel title="Lecture workflow"><p>Open practice questions, flashcards, and uploaded resources linked to this lecture.</p><Link className="pp-button" href={`/past-exams?bundle=${bundleId}&lecture=${selected.id}&mode=TUTOR`}>Start tutor questions</Link> <Link className="pp-button secondary" href={`/flashcards?bundle=${bundleId}&lecture=${selected.id}`}>Review flashcards</Link></Panel></>:<Panel title="No lectures"><p>This course has no visible lectures yet.</p></Panel>}</article><aside className="guide-side"><Panel title="Course coverage"><b className="pp-big">{lectures.length}<small> lectures</small></b><Progress value={lectures.length?100:0}/></Panel><Panel title="Data source"><p><FiFileText/> Every course, week, and lecture is loaded from the selected bundle entitlement. No unrestricted academic catalog is used.</p></Panel></aside></div>}</main></ProductShell>;
}
