"use client";

import { ApiError } from "@/lib/api";
import { useCallback, useEffect, useRef, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { FiBookOpen, FiCheck, FiRefreshCw, FiRotateCcw, FiWifiOff } from "react-icons/fi";
import { useAuth } from "./auth-provider";
import { PageSkeleton } from "./async-state";
import { Panel, ProductShell, Progress } from "./product-shell";
import { useUx } from "./ux-provider";
import "./product-pages.css";

type Deck={id:string;title:string;lecture?:{id?:string;title?:string;week?:{title?:string;weekNumber?:number}};course?:{courseName?:string}};
type Card={id:string;title:string;frontContent:string;backContent:string;explanation?:string|null;deck:Deck};
type Page<T>={data:T[];page:number;limit:number;total:number;total_pages:number};
type Rating="VERY_HARD"|"HARD"|"GOOD"|"EASY";
type PendingReview={token:string;card:Card;rating:Rating;createdAt:number;originalIndex:number};
type StoredSession={reviewed:number;selectedCardId:string|null;pending:PendingReview[]};
const numberRatings:Record<string,Rating>={"1":"VERY_HARD","2":"HARD","3":"GOOD","4":"EASY"};
const REVIEW_UNDO_MS=5000;

export function ConnectedFlashcardsPage(){
 const {user,request}=useAuth();const {startNavigation,notify}=useUx();const router=useRouter();const pathname=usePathname();const searchParams=useSearchParams();
 const requestedCard=searchParams.get("card");const requestedLecture=searchParams.get("lecture");
 const [cards,setCards]=useState<Card[]>([]);const [index,setIndex]=useState(0);const [revealed,setRevealed]=useState(false);const [reviewed,setReviewed]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [online,setOnline]=useState(true);const [pending,setPending]=useState<PendingReview[]>([]);const [dragX,setDragX]=useState(0);
 const pendingRef=useRef<PendingReview[]>([]);const timers=useRef(new Map<string,number>());const pointerStart=useRef<{x:number;y:number}|null>(null);const swiped=useRef(false);
 const sessionKey=`mdp-flashcard-session:${user?.id||"anonymous"}`;

 const setUrl=useCallback((card:Card|null,replace=false)=>{const params=new URLSearchParams(searchParams.toString());if(card){params.set("card",card.id);if(card.deck.lecture?.id)params.set("lecture",card.deck.lecture.id);}else params.delete("card");const suffix=params.toString();const href=suffix?`${pathname}?${suffix}`:pathname;startNavigation();if(replace)router.replace(href,{scroll:false});else router.push(href,{scroll:false});},[pathname,router,searchParams,startNavigation]);
 const readSession=useCallback(()=>{try{return JSON.parse(localStorage.getItem(sessionKey)||"null") as StoredSession|null;}catch{return null;}},[sessionKey]);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const session=readSession();const result=await request<Page<Card>>("/flashcards/cards/due?limit=50");const hidden=new Set((session?.pending||[]).map(item=>item.card.id));setReviewed(session?.reviewed||0);setPending(session?.pending||[]);setCards(result.data.filter(item=>!hidden.has(item.id)));}catch(cause){setError(cause instanceof ApiError?cause.message:"Unable to load due flashcards.");}finally{setLoading(false);}},[readSession,request]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{pendingRef.current=pending;try{localStorage.setItem(sessionKey,JSON.stringify({reviewed,selectedCardId:cards[index]?.id||null,pending} satisfies StoredSession));}catch{}},[cards,index,pending,reviewed,sessionKey]);
 useEffect(()=>{if(loading||!cards.length)return;const stored=readSession();const cardIndex=requestedCard?cards.findIndex(item=>item.id===requestedCard):-1;const lectureIndex=requestedLecture?cards.findIndex(item=>item.deck.lecture?.id===requestedLecture):-1;const storedIndex=stored?.selectedCardId?cards.findIndex(item=>item.id===stored.selectedCardId):-1;const targetIndex=cardIndex>=0?cardIndex:lectureIndex>=0?lectureIndex:storedIndex>=0?storedIndex:0;setIndex(targetIndex);setRevealed(false);if(requestedCard!==cards[targetIndex]?.id)setUrl(cards[targetIndex],true);},[cards,loading,readSession,requestedCard,requestedLecture,setUrl]);
 useEffect(()=>{setOnline(navigator.onLine);const goOnline=()=>setOnline(true);const goOffline=()=>setOnline(false);window.addEventListener("online",goOnline);window.addEventListener("offline",goOffline);return()=>{window.removeEventListener("online",goOnline);window.removeEventListener("offline",goOffline);};},[]);

 const restoreReview=useCallback((entry:PendingReview,message?:string)=>{setCards(current=>{if(current.some(item=>item.id===entry.card.id))return current;const next=[...current];next.splice(Math.min(entry.originalIndex,next.length),0,entry.card);return next;});setReviewed(value=>Math.max(0,value-1));setIndex(Math.min(entry.originalIndex,cards.length));setRevealed(true);setUrl(entry.card,true);if(message)notify({title:"Review restored",description:message,tone:"error"});},[cards.length,notify,setUrl]);
 const removePending=useCallback((token:string)=>{setPending(current=>current.filter(item=>item.token!==token));const timer=timers.current.get(token);if(timer)window.clearTimeout(timer);timers.current.delete(token);},[]);
 const commitReview=useCallback(async(entry:PendingReview)=>{if(!navigator.onLine)return;try{await request(`/flashcards/cards/${entry.card.id}/review`,{method:"POST",body:{rating:entry.rating}});removePending(entry.token);}catch(cause){removePending(entry.token);restoreReview(entry,cause instanceof Error?cause.message:"The review could not be saved.");}},[removePending,request,restoreReview]);
 const undoReview=useCallback((token:string)=>{const entry=pendingRef.current.find(item=>item.token===token);if(!entry)return;removePending(token);restoreReview(entry);notify({title:"Review undone",description:"The card is back in your queue.",tone:"info",duration:2500});},[notify,removePending,restoreReview]);
 useEffect(()=>{if(!online)return;for(const entry of pending){if(timers.current.has(entry.token))continue;const remaining=Math.max(0,entry.createdAt+REVIEW_UNDO_MS-Date.now());const timer=window.setTimeout(()=>{timers.current.delete(entry.token);void commitReview(entry);},remaining);timers.current.set(entry.token,timer);}return()=>{};},[commitReview,online,pending]);
 useEffect(()=>()=>{for(const timer of timers.current.values())window.clearTimeout(timer);timers.current.clear();},[]);

 const card=cards[index];
 const selectCard=useCallback((nextIndex:number)=>{const next=Math.max(0,Math.min(cards.length-1,nextIndex));setIndex(next);setRevealed(false);setDragX(0);if(cards[next])setUrl(cards[next]);},[cards,setUrl]);
 const rate=useCallback((rating:Rating)=>{if(!card)return;const entry:PendingReview={token:crypto.randomUUID(),card,rating,createdAt:Date.now(),originalIndex:index};const remaining=cards.filter(item=>item.id!==card.id);setPending(current=>[...current,entry]);setReviewed(value=>value+1);setCards(remaining);setIndex(0);setRevealed(false);setUrl(remaining[0]||null,true);notify({title:"Review queued",description:online?"It will sync after the undo window closes.":"It is saved locally and will sync when you reconnect.",tone:"success",duration:REVIEW_UNDO_MS,actionLabel:"Undo",onAction:()=>undoReview(entry.token)});},[card,cards,index,notify,online,setUrl,undoReview]);
 useEffect(()=>{function handleKey(event:KeyboardEvent){const target=event.target as HTMLElement|null;if(target&&(target.isContentEditable||["INPUT","TEXTAREA","SELECT","BUTTON"].includes(target.tagName)))return;if(!card)return;if(event.code==="Space"){event.preventDefault();setRevealed(value=>!value);}else if(event.key==="ArrowRight"){event.preventDefault();selectCard(index+1);}else if(event.key==="ArrowLeft"){event.preventDefault();selectCard(index-1);}else if(revealed&&numberRatings[event.key]){event.preventDefault();rate(numberRatings[event.key]);}}window.addEventListener("keydown",handleKey);return()=>window.removeEventListener("keydown",handleKey);},[card,index,rate,revealed,selectCard]);
 function pointerDown(event:React.PointerEvent<HTMLButtonElement>){pointerStart.current={x:event.clientX,y:event.clientY};swiped.current=false;event.currentTarget.setPointerCapture(event.pointerId);}
 function pointerMove(event:React.PointerEvent<HTMLButtonElement>){if(!pointerStart.current)return;const dx=event.clientX-pointerStart.current.x,dy=event.clientY-pointerStart.current.y;if(Math.abs(dx)>Math.abs(dy))setDragX(Math.max(-120,Math.min(120,dx)));}
 function pointerUp(){if(!pointerStart.current)return;const dx=dragX;pointerStart.current=null;if(Math.abs(dx)>=65){swiped.current=true;selectCard(index+(dx<0?1:-1));}setDragX(0);}

 return <ProductShell search="Search flashcards or lectures"><main className="pp-page flashcards-page"><div className="pp-title hero"><div><small className="page-eyebrow">SPACED REPETITION</small><h1>Flashcards</h1><p>Review instructor-published cards when they become due.</p></div><div className="keyboard-hints" aria-label="Keyboard and touch shortcuts"><span>Space · Flip</span><span>← → · Navigate</span><span>Swipe · Navigate</span><span>1–4 · Rate</span></div></div>
 {!online&&<p className="offline-notice" role="status"><FiWifiOff/> Offline reviews stay on this device and sync when your connection returns.</p>}{pending.length>0&&<p className="pending-review-notice" role="status"><FiRotateCcw/> {pending.length} review{pending.length===1?"":"s"} waiting for the Undo window or network sync.</p>}{error&&<p className="form-error" role="alert">{error} <button onClick={()=>void load()}>Retry</button></p>}
 {loading?<PageSkeleton variant="workspace" label="Loading your review queue"/>:!card?<Panel title={pending.length?"Reviews waiting to sync":"You are caught up"}><FiCheck/><h2>{pending.length?"Your visible queue is complete.":"No flashcards are due right now."}</h2><p>You reviewed {reviewed} card{reviewed===1?"":"s"} in this session.</p><button className="pp-button secondary" onClick={()=>void load()}>Refresh queue</button></Panel>:<div className="flashcards-layout connected"><aside className="deck-sidebar"><div className="deck-sidebar-head"><span><b>DUE QUEUE</b><small>{cards.length} cards remaining</small></span></div>{cards.map((item,itemIndex)=><button className={index===itemIndex?"active":""} onClick={()=>selectCard(itemIndex)} key={item.id}><span><small>{item.deck.course?.courseName||"Course"}</small><b>{item.deck.title}</b><em>{item.title}</em></span></button>)}</aside>
 <section className="review-workspace"><div className="review-heading"><div><small>{card.deck.lecture?.week?.title||"Instructor deck"}</small><h2>{card.deck.title}</h2><p>{card.deck.lecture?.title||card.title}</p></div><div><b>{reviewed}</b><small>reviewed now</small></div></div><button className={`study-card single-face ${revealed?"showing-back":"showing-front"} ${dragX?"is-dragging":""}`} style={{transform:`translateX(${dragX}px) rotate(${dragX/30}deg)`}} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={()=>{pointerStart.current=null;setDragX(0);}} onClick={()=>{if(swiped.current){swiped.current=false;return;}setRevealed(value=>!value);}} aria-pressed={revealed}><div className="study-card-inner"><div className={`card-face ${revealed?"card-back":"card-front"}`}>{revealed?<><small>BACK · EXPLANATION</small><p>{card.backContent}</p>{card.explanation&&<p>{card.explanation}</p>}<span>Click or press Space to see the front</span></>:<><small>FRONT</small><FiBookOpen/><h2>{card.frontContent}</h2><span>Click, press Space, or swipe to navigate</span></>}</div></div></button>{revealed&&<div className="review-rating"><p>How well did you remember?</p><button onClick={()=>rate("VERY_HARD")} className="again"><b>1 · Again</b></button><button onClick={()=>rate("HARD")}><b>2 · Hard</b></button><button onClick={()=>rate("GOOD")} className="good"><b>3 · Good</b></button><button onClick={()=>rate("EASY")}><b>4 · Easy</b></button></div>}</section>
 <aside className="flashcard-insights"><Panel title="Today’s progress"><div className="readiness-ring">{reviewed}<small>reviewed</small></div><Progress value={cards.length+reviewed?Math.round(reviewed/(cards.length+reviewed)*100):100}/></Panel><Panel title="How review works"><p><FiRefreshCw/> Ratings are queued locally for five seconds.</p><p>Undo restores the card before the backend schedule changes.</p><p>Offline reviews resume automatically after reconnection.</p></Panel></aside></div>}
 </main></ProductShell>;
}