"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { FiBookOpen, FiChevronRight, FiFileText } from "react-icons/fi";
import { useAuth } from "./auth-provider";
import { Panel, ProductShell, Progress } from "./product-shell";
import "./product-pages.css";

type Course={id:string;courseName:string;courseCode:string;description:string|null};
type Lecture={id:string;title:string;description:string|null;lectureNumber:number;isPublished:boolean};
type Week={id:string;weekNumber:number;title:string|null;description:string|null;lectures?:Lecture[]};
type Page<T>={data:T[]};

export function ConnectedRoundsPage(){
 const {request}=useAuth();const [courses,setCourses]=useState<Course[]>([]);const [courseId,setCourseId]=useState("");const [weeks,setWeeks]=useState<Week[]>([]);const [selected,setSelected]=useState<Lecture|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
 useEffect(()=>{let active=true;void request<Page<Course>>("/academic/courses?limit=100").then(result=>{if(active){setCourses(result.data);setCourseId(result.data[0]?.id||"");}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Unable to load courses.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[request]);
 useEffect(()=>{if(!courseId)return;let active=true;void (async()=>{try{const weekPage=await request<Page<Week>>(`/academic/courses/${courseId}/weeks?limit=100`);const hydrated=await Promise.all(weekPage.data.map(async week=>({...week,lectures:(await request<Page<Lecture>>(`/academic/weeks/${week.id}/lectures?limit=100`)).data})));if(active){setWeeks(hydrated);setSelected(hydrated.flatMap(item=>item.lectures||[])[0]||null);setError(null);}}catch(cause){if(active)setError(cause instanceof Error?cause.message:"Unable to load lectures.");}})();return()=>{active=false};},[courseId,request]);
 const course=courses.find(item=>item.id===courseId);const lectures=weeks.flatMap(week=>(week.lectures||[]).map(lecture=>({week,lecture})));return <ProductShell search="Search courses or lectures"><main className="pp-page"><div className="pp-title"><div><h1>Rounds &amp; Lectures</h1><p>Browse the academic structure currently published by instructors.</p></div><label>Course<select value={courseId} onChange={event=>setCourseId(event.target.value)}>{courses.map(item=><option key={item.id} value={item.id}>{item.courseCode} · {item.courseName}</option>)}</select></label></div>{error&&<p className="form-error" role="alert">{error}</p>}{loading?<div className="product-auth-loading">Loading curriculum…</div>:!course?<Panel title="No courses available"><p>No active course is currently available to this account.</p></Panel>:<div className="study-guide-layout"><aside className="guide-course-nav"><div className="guide-course"><small>COURSE</small><b>{course.courseName}</b></div>{weeks.map(week=><section key={week.id}><div><b>Week {week.weekNumber}</b><small>{week.title||"Untitled week"}</small></div>{(week.lectures||[]).map(lecture=><button className={selected?.id===lecture.id?"active":""} onClick={()=>setSelected(lecture)} key={lecture.id}><FiBookOpen/><span>{lecture.lectureNumber}. {lecture.title}</span><FiChevronRight/></button>)}</section>)}</aside><article className="guide-content">{selected?<><div className="guide-hero"><span><FiBookOpen/></span><div><small>LECTURE {selected.lectureNumber}</small><h1>{selected.title}</h1><p>{selected.description||"No description has been published for this lecture."}</p></div></div><Panel title="Lecture workflow"><p>Open practice questions, flashcards, and uploaded resources linked to this lecture.</p><Link className="pp-button" href="/past-exams">Practice questions</Link> <Link className="pp-button secondary" href="/flashcards">Review flashcards</Link></Panel></>:<Panel title="No lectures"><p>This course has no visible lectures yet.</p></Panel>}</article><aside className="guide-side"><Panel title="Course coverage"><b className="pp-big">{lectures.length}<small> lectures</small></b><Progress value={lectures.length?100:0}/></Panel><Panel title="Data source"><p><FiFileText/> Courses, weeks, and lectures are loaded from the Academic API. No sample curriculum is injected by the frontend.</p></Panel></aside></div>}</main></ProductShell>;
}
