"use client";
import { FormEvent, useEffect, useState } from "react";
import { FiEdit3, FiPlus, FiRefreshCw, FiTrash2 } from "react-icons/fi";
import { useAuth } from "./auth-provider";
import { Panel, ProductShell } from "./product-shell";
import { useUx } from "./ux-provider";
import "./pdf-essay-cases.css";
import "./instructor-essay-case-studio.css";
import "./role-workspace.css";
type Course={id:string;courseCode:string;courseName:string}; type Q={id?:string;prompt:string;model_answer:string}; type Case={id:string;weekId:string;weekNumber:number;title:string;stem:string;section:string|null;sourceCaseNumber:number|null;isPublished:boolean;questions:Array<{id:string;prompt:string;modelAnswer?:string}>}; type Week={id:string;weekNumber:number;title:string|null;cases:Array<{id:string;title:string;stem:string;section:string|null;isPublished:boolean;questions:unknown[]}>}; type Curriculum={weeks:Week[]};
const empty={id:"",week_id:"",title:"",stem:"",section:"",is_published:false,questions:[{prompt:"",model_answer:""}] as Q[]};
export function InstructorEssayCaseStudio(){const {request}=useAuth();const {notify}=useUx();const [courses,setCourses]=useState<Course[]>([]);const [courseId,setCourseId]=useState("");const [curriculum,setCurriculum]=useState<Curriculum|null>(null);const [form,setForm]=useState(empty);const [editing,setEditing]=useState(false);const [saving,setSaving]=useState(false);
 async function load(id=courseId){if(!id)return;setCurriculum(await request<Curriculum>(`/essay-cases?course_id=${encodeURIComponent(id)}`))}
 useEffect(()=>{request<Course[]>("/essay-cases/courses").then(items=>{setCourses(items);setCourseId(items[0]?.id||"")})},[request]); useEffect(()=>{if(courseId)void load(courseId)},[courseId]);
 function create(weekId:string){setForm({...empty,week_id:weekId,questions:[{prompt:"",model_answer:""}]});setEditing(true)}
 async function edit(id:string){const item=await request<Case>(`/essay-cases/${id}`);setForm({id:item.id,week_id:item.weekId,title:item.title,stem:item.stem,section:item.section||"",is_published:item.isPublished,questions:item.questions.map(q=>({id:q.id,prompt:q.prompt,model_answer:q.modelAnswer||""}))});setEditing(true)}
 function count(value:number){setForm(v=>({...v,questions:Array.from({length:value},(_,i)=>v.questions[i]||{prompt:"",model_answer:""})}))}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);try{const body={week_id:form.week_id,title:form.title.trim(),stem:form.stem.trim(),section:form.section.trim()||undefined,is_published:form.is_published,questions:form.questions.map(q=>({id:q.id,prompt:q.prompt.trim(),model_answer:q.model_answer.trim()}))};await request(form.id?`/essay-cases/${form.id}`:"/essay-cases",{method:form.id?"PUT":"POST",body:form.id?{...body,week_id:undefined}:body});notify({title:form.id?"Case updated":"Case created",tone:"success"});setEditing(false);await load()}catch(e){notify({title:"Could not save case",description:e instanceof Error?e.message:undefined,tone:"error"})}finally{setSaving(false)}}
 async function remove(id:string){if(!window.confirm("Delete this case and its questions?"))return;await request(`/essay-cases/${id}`,{method:"DELETE"});await load()}
 async function importPdf(){setSaving(true);try{const r=await request<{imported:number;skipped:number}>("/essay-cases/imports/summer-uro-nephrology",{method:"POST",body:{course_id:courseId}});notify({title:`Imported ${r.imported} PDF cases`,description:`${r.skipped} already existed.`,tone:"success"});await load()}catch(e){notify({title:"Could not import PDF cases",description:e instanceof Error?e.message:undefined,tone:"error"})}finally{setSaving(false)}}
 return <ProductShell search="Search essay cases"><main className="pp-page role-workspace"><div className="pp-title hero role-heading"><div><small className="page-eyebrow">INSTRUCTOR · ESSAY CASE STUDIO</small><h1>Essay cases</h1><p>Create and edit the case-based curriculum. Every sub-question stores the exact model answer students reveal after submitting.</p></div><div className="role-heading-actions"><button className="pp-button secondary" disabled={!courseId||saving} onClick={()=>void importPdf()}><FiRefreshCw/> Import Summer PDF</button></div></div><label className="essay-course-select">Course<select value={courseId} onChange={e=>setCourseId(e.target.value)}>{courses.map(c=><option key={c.id} value={c.id}>{c.courseCode} · {c.courseName}</option>)}</select></label>
 <div className="instructor-case-weeks">{curriculum?.weeks.map(week=><Panel key={week.id} title={`Week ${week.weekNumber}${week.title?` · ${week.title}`:""}`}><div className="instructor-case-list">{week.cases.map(item=><article key={item.id}><div><b>{item.title}</b><small>{item.questions.length} questions · {item.isPublished?"Published":"Draft"}</small></div><span><button type="button" onClick={()=>void edit(item.id)}><FiEdit3/> Edit</button><button className="danger" type="button" onClick={()=>void remove(item.id)}><FiTrash2/></button></span></article>)}</div><button className="pp-button secondary" type="button" onClick={()=>create(week.id)}><FiPlus/> New case in Week {week.weekNumber}</button></Panel>)}</div>
 {editing&&<div className="role-modal-backdrop"><section className="role-modal wide"><header><h2>{form.id?"Edit case":"Create case"}</h2><button onClick={()=>setEditing(false)}>×</button></header><form className="role-form" onSubmit={save}><div className="role-form-grid"><label>Title<input required value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></label><label>Section<input value={form.section} onChange={e=>setForm(v=>({...v,section:e.target.value}))}/></label><label className="wide">Case study<textarea required rows={7} value={form.stem} onChange={e=>setForm(v=>({...v,stem:e.target.value}))}/></label><label>Number of questions<select value={form.questions.length} onChange={e=>count(Number(e.target.value))}>{Array.from({length:20},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label><label className="case-publish"><input type="checkbox" checked={form.is_published} onChange={e=>setForm(v=>({...v,is_published:e.target.checked}))}/> Published to students</label></div><div className="case-question-editor">{form.questions.map((q,i)=><Panel key={i} title={`Question ${i+1}`}><label>Question<textarea required rows={3} value={q.prompt} onChange={e=>setForm(v=>({...v,questions:v.questions.map((x,n)=>n===i?{...x,prompt:e.target.value}:x)}))}/></label><label>Model answer shown after reveal<textarea required rows={5} value={q.model_answer} onChange={e=>setForm(v=>({...v,questions:v.questions.map((x,n)=>n===i?{...x,model_answer:e.target.value}:x)}))}/></label></Panel>)}</div><footer><button className="pp-button secondary" type="button" onClick={()=>setEditing(false)}>Cancel</button><button className="pp-button" disabled={saving} type="submit">{saving?"Saving…":"Save case"}</button></footer></form></section></div>}</main></ProductShell>}
