[CmdletBinding()]
param(
    [string]$EnvFilePath = 'backend/.env',
    [string]$Repository = 'EyadAhmed06/My-Doctor-Professor',
    [string]$DeployRoleArn = 'arn:aws:iam::755611554099:role/my-doctor-professor-production-github-deploy',
    [string]$ProductionUrl = 'https://18-102-130-45.sslip.io',
    [string]$WorkloadRegion = 'eu-south-1',
    [string]$AnatomyAssetBase = '',
    [switch]$Deploy
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Assert-Command {
    param([Parameter(Mandatory)][string]$Name)
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        throw "Required command '$Name' was not found in PATH."
    }
}

function Invoke-Gh {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]]$Arguments)
    & gh @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "GitHub CLI command failed ($LASTEXITCODE): gh $($Arguments -join ' ')"
    }
}

function Get-EnvValue {
    param(
        [Parameter(Mandatory)][string]$Content,
        [Parameter(Mandatory)][string]$Name
    )

    $Match = [regex]::Match($Content, "(?m)^\s*$([regex]::Escape($Name))\s*=\s*(.*)\s*$")
    if (-not $Match.Success) { return '' }
    $Value = $Match.Groups[1].Value.Trim()
    if (($Value.StartsWith('"') -and $Value.EndsWith('"')) -or ($Value.StartsWith("'") -and $Value.EndsWith("'"))) {
        $Value = $Value.Substring(1, $Value.Length - 2)
    }
    return $Value
}

function Assert-RealValue {
    param(
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][string]$Value
    )
    if ([string]::IsNullOrWhiteSpace($Value)) {
        throw "Required production setting '$Name' is missing from the source env file."
    }
    if ($Value -match '(?i)replace|your_|example|placeholder|changeme') {
        throw "Production setting '$Name' still looks like a placeholder."
    }
}

Assert-Command gh

& gh auth status *> $null
if ($LASTEXITCODE -ne 0) {
    throw "GitHub CLI is not authenticated. Run 'gh auth login' first."
}

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$ResolvedEnvPath = if ([System.IO.Path]::IsPathRooted($EnvFilePath)) {
    $EnvFilePath
} else {
    Join-Path $RepoRoot $EnvFilePath
}

if (-not (Test-Path -LiteralPath $ResolvedEnvPath -PathType Leaf)) {
    throw "Source env file '$ResolvedEnvPath' was not found. Pass -EnvFilePath with the local backend env that contains the real Google/SMTP/JWT secrets."
}

$Source = [System.IO.File]::ReadAllText($ResolvedEnvPath)
$Source = $Source -replace "`r`n", "`n"

$GoogleClientId = Get-EnvValue -Content $Source -Name 'GOOGLE_CLIENT_ID'
$SmtpHost = Get-EnvValue -Content $Source -Name 'SMTP_HOST'
$SmtpPort = Get-EnvValue -Content $Source -Name 'SMTP_PORT'
$SmtpUser = Get-EnvValue -Content $Source -Name 'SMTP_USER'
$SmtpPassword = Get-EnvValue -Content $Source -Name 'SMTP_PASSWORD'
$SmtpFrom = Get-EnvValue -Content $Source -Name 'SMTP_FROM'
$JwtSecret = Get-EnvValue -Content $Source -Name 'JWT_SECRET'
$JwtRefreshSecret = Get-EnvValue -Content $Source -Name 'JWT_REFRESH_SECRET'
$OutboxKey = Get-EnvValue -Content $Source -Name 'EMAIL_OUTBOX_ENCRYPTION_KEY'
$AllowBootstrap = Get-EnvValue -Content $Source -Name 'ALLOW_ACCOUNT_BOOTSTRAP'
$BootstrapToken = Get-EnvValue -Content $Source -Name 'ACCOUNT_BOOTSTRAP_TOKEN'

Assert-RealValue GOOGLE_CLIENT_ID $GoogleClientId
Assert-RealValue SMTP_HOST $SmtpHost
Assert-RealValue SMTP_PORT $SmtpPort
Assert-RealValue SMTP_USER $SmtpUser
Assert-RealValue SMTP_PASSWORD $SmtpPassword
Assert-RealValue SMTP_FROM $SmtpFrom
Assert-RealValue JWT_SECRET $JwtSecret
Assert-RealValue JWT_REFRESH_SECRET $JwtRefreshSecret
Assert-RealValue EMAIL_OUTBOX_ENCRYPTION_KEY $OutboxKey

if ($GoogleClientId -notmatch '^[0-9]+-[A-Za-z0-9_-]+\.apps\.googleusercontent\.com$') {
    throw 'GOOGLE_CLIENT_ID is not a valid Google Web application client ID.'
}
if ($SmtpPort -notmatch '^\d+$') {
    throw 'SMTP_PORT must be numeric.'
}
if ($SmtpHost -in @('localhost', '127.0.0.1', '::1')) {
    throw 'SMTP_HOST must point to the real external mail provider.'
}
if ($JwtSecret.Length -lt 32 -or $JwtRefreshSecret.Length -lt 32) {
    throw 'JWT_SECRET and JWT_REFRESH_SECRET must each be at least 32 characters.'
}
if ($JwtSecret -eq $JwtRefreshSecret) {
    throw 'JWT_SECRET and JWT_REFRESH_SECRET must be different.'
}
if ($AllowBootstrap -match '^(?i:true|1|yes)$') {
    Assert-RealValue ACCOUNT_BOOTSTRAP_TOKEN $BootstrapToken
    if ($BootstrapToken.Length -lt 32) {
        throw 'ACCOUNT_BOOTSTRAP_TOKEN must be at least 32 characters when account bootstrap is enabled.'
    }
}

# Database credentials are generated by Terraform and injected from a separate
# encrypted SSM parameter. Runtime/container-managed values are also normalized
# here so stale settings from the previous AWS account cannot leak into the new deployment.
$ManagedNames = @(
    'DB_HOST','DB_PORT','DB_USERNAME','DB_PASSWORD','DB_NAME','DB_SSL_ENABLED','DB_SSL_REJECT_UNAUTHORIZED','DB_SSL_CA_PATH',
    'NODE_ENV','PORT','TRUST_PROXY_HOPS','FRONTEND_URL','AUTH_COOKIE_PATH','FILE_UPLOAD_PATH','BACKUP_DIR','LOG_LEVEL'
)
$ManagedPattern = '^\s*(' + (($ManagedNames | ForEach-Object { [regex]::Escape($_) }) -join '|') + ')\s*='
$PreservedLines = @()
foreach ($Line in ($Source -split "`n")) {
    if ($Line -match $ManagedPattern) { continue }
    $PreservedLines += $Line.TrimEnd("`r")
}

$ProductionEnv = (($PreservedLines -join "`n").TrimEnd() + "`n" + @"

# Values normalized for the Milan production host.
NODE_ENV=production
PORT=3000
TRUST_PROXY_HOPS=1
FRONTEND_URL=$ProductionUrl
AUTH_COOKIE_PATH=/api/v1/auth
FILE_UPLOAD_PATH=/app/uploads
BACKUP_DIR=/app/backups
LOG_LEVEL=info
"@).Trim() + "`n"

Write-Host "Configuring GitHub repository deployment settings for $Repository..." -ForegroundColor Cyan
Invoke-Gh variable set AWS_DEPLOY_ROLE_ARN --repo $Repository --body $DeployRoleArn
Invoke-Gh variable set AWS_WORKLOAD_REGION --repo $Repository --body $WorkloadRegion
Invoke-Gh variable set NEXT_PUBLIC_GOOGLE_CLIENT_ID --repo $Repository --body $GoogleClientId

if (-not [string]::IsNullOrWhiteSpace($AnatomyAssetBase)) {
    $NormalizedAnatomyBase = $AnatomyAssetBase.TrimEnd('/')
    Invoke-Gh variable set NEXT_PUBLIC_ANATOMY_ASSET_BASE --repo $Repository --body $NormalizedAnatomyBase
    Write-Host 'Configured NEXT_PUBLIC_ANATOMY_ASSET_BASE from the supplied value.' -ForegroundColor Green
}
else {
    $ExistingAnatomyBase = (& gh variable get NEXT_PUBLIC_ANATOMY_ASSET_BASE --repo $Repository --body 2>$null)
    if ($LASTEXITCODE -eq 0 -and -not [string]::IsNullOrWhiteSpace(($ExistingAnatomyBase | Out-String).Trim())) {
        Write-Host 'Preserving the existing NEXT_PUBLIC_ANATOMY_ASSET_BASE repository variable.' -ForegroundColor Green
    }
    else {
        Write-Warning 'NEXT_PUBLIC_ANATOMY_ASSET_BASE is not configured. The app can deploy, but anatomy .glb models are gitignored and the anatomy viewer will not have its production model origin until this variable is set.'
    }
}

$TempFile = Join-Path $env:TEMP 'mdp-production.env'
try {
    [System.IO.File]::WriteAllText($TempFile, $ProductionEnv, [System.Text.UTF8Encoding]::new($false))
    Get-Content -Raw -LiteralPath $TempFile | & gh secret set PRODUCTION_ENV_FILE --repo $Repository
    if ($LASTEXITCODE -ne 0) {
        throw 'Failed to store PRODUCTION_ENV_FILE in GitHub Actions secrets.'
    }
}
finally {
    Remove-Item -LiteralPath $TempFile -Force -ErrorAction SilentlyContinue
}

Write-Host 'GitHub production configuration is ready.' -ForegroundColor Green
Write-Host "Production origin: $ProductionUrl"
Write-Host "Google client ID: configured for backend + frontend"
Write-Host 'SMTP/JWT/outbox secrets: validated and stored without printing values'
Write-Host 'Database credentials: intentionally excluded; Terraform/SSM owns them'

if ($Deploy) {
    Write-Host "`nTriggering Deploy AWS production on infra/aws-redeploy-iac..." -ForegroundColor Yellow
    Invoke-Gh workflow run deploy-aws-production.yml --repo $Repository --ref infra/aws-redeploy-iac -f confirm=DEPLOY
    Write-Host 'Deployment workflow triggered. Use GitHub Actions or gh run list to follow it.' -ForegroundColor Green
}
else {
    Write-Host "`nConfiguration only. Re-run with -Deploy when you want to trigger the deployment." -ForegroundColor Cyan
}
