import { UserRole } from '../users/entities/user.entity';
import { Body, Controller, Delete, Get, NotImplementedException, Param, Post, Put, Query, UseGuards } from '@nestjs/common';
import { Roles } from '../auth/decorators/roles.decorator'; import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard'; import { RolesGuard } from '../auth/guards/roles.guard';
@Controller('tests') @UseGuards(JwtAuthGuard,RolesGuard)
export class TestsController { private pending():never{throw new NotImplementedException('Assessment workflow will be implemented after DTO contracts');}
 @Post() @Roles(UserRole.INSTRUCTOR,UserRole.SYSTEM_ADMIN) create(@Body() _body:unknown){return this.pending();} @Get() list(@Query() _query:Record<string,string>){return this.pending();} @Get(':testId') getOne(@Param('testId') _id:string){return this.pending();} @Put(':testId') @Roles(UserRole.INSTRUCTOR,UserRole.SYSTEM_ADMIN) update(@Param('testId') _id:string,@Body() _body:unknown){return this.pending();} @Delete(':testId') @Roles(UserRole.INSTRUCTOR,UserRole.SYSTEM_ADMIN) remove(@Param('testId') _id:string){return this.pending();}
 @Post(':testId/questions') @Roles(UserRole.INSTRUCTOR,UserRole.SYSTEM_ADMIN) addQuestion(@Param('testId') _id:string,@Body() _body:unknown){return this.pending();} @Get(':testId/questions') listQuestions(@Param('testId') _id:string){return this.pending();} @Delete(':testId/questions/:questionId') @Roles(UserRole.INSTRUCTOR,UserRole.SYSTEM_ADMIN) removeQuestion(@Param('testId') _testId:string,@Param('questionId') _questionId:string){return this.pending();}
 @Get(':testId/attempts') @Roles(UserRole.INSTRUCTOR,UserRole.SYSTEM_ADMIN) listAttempts(@Param('testId') _id:string){return this.pending();} @Post(':testId/attempts') @Roles(UserRole.STUDENT) startAttempt(@Param('testId') _id:string,@Body() _body:unknown){return this.pending();}
 @Get('attempts/:attemptId') getAttempt(@Param('attemptId') _id:string){return this.pending();} @Put('attempts/:attemptId/answers/:questionId') @Roles(UserRole.STUDENT) saveAnswer(@Param('attemptId') _attemptId:string,@Param('questionId') _questionId:string,@Body() _body:unknown){return this.pending();} @Post('attempts/:attemptId/submit') @Roles(UserRole.STUDENT) submit(@Param('attemptId') _id:string){return this.pending();}
 @Get('attempts/:attemptId/answers') getAnswers(@Param('attemptId') _id:string){return this.pending();} @Get('attempts/:attemptId/review') getReview(@Param('attemptId') _id:string){return this.pending();}
 @Post('attempts/:attemptId/flags/:questionId') @Roles(UserRole.STUDENT) flag(@Param('attemptId') _attemptId:string,@Param('questionId') _questionId:string){return this.pending();} @Delete('attempts/:attemptId/flags/:questionId') @Roles(UserRole.STUDENT) unflag(@Param('attemptId') _attemptId:string,@Param('questionId') _questionId:string){return this.pending();}
 @Post('attempts/:attemptId/notes/:questionId') @Roles(UserRole.STUDENT) addNote(@Param('attemptId') _attemptId:string,@Param('questionId') _questionId:string,@Body() _body:unknown){return this.pending();} @Put('attempts/:attemptId/notes/:questionId') @Roles(UserRole.STUDENT) updateNote(@Param('attemptId') _attemptId:string,@Param('questionId') _questionId:string,@Body() _body:unknown){return this.pending();} @Delete('attempts/:attemptId/notes/:questionId') @Roles(UserRole.STUDENT) removeNote(@Param('attemptId') _attemptId:string,@Param('questionId') _questionId:string){return this.pending();}
 @Put('attempts/:attemptId/answers/:answerId/grade') @Roles(UserRole.INSTRUCTOR,UserRole.SYSTEM_ADMIN) gradeEssay(@Param('attemptId') _attemptId:string,@Param('answerId') _answerId:string,@Body() _body:unknown){return this.pending();}
}
